version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: visionx-db
    restart: always
    environment:
      POSTGRES_USER: visionx_user
      POSTGRES_PASSWORD: visionx_password
      POSTGRES_DB: visionx_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: visionx-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://visionx_user:visionx_password@db:5432/visionx_db
      - GROQ_API_KEY=${GROQ_API_KEY}

    depends_on:
      - db

volumes:
  postgres_data:
